const level1 = new Level(
  [
    new JellyPurple(),
    new JellyPurple(),
    new JellyPurple(),
    new JellyPurple(),
    new JellyPink(),
    new JellyPink(),
    new JellyPink(),
    new JellyGreen(),
    new JellyGreen(),
    new JellyGreen(),
    new PufferGreen(),
    new PufferGreen(),
    new PufferGreen(),
    new PufferBubble(),
    new PufferBubble(),
    new PufferBubble(),
    new PufferRed(),
    new PufferRed(),
    new PufferRed(),
    new Endboss(),
  ],
  [
    new BackgroundObject("../img/3. Background/Layers/5. Water/D2.png", -900),
    new BackgroundObject("../img/3. Background/Layers/4.Fondo 2/D2.png", -900),
    new BackgroundObject("../img/3. Background/Layers/3.Fondo 1/L2.png", -900),
    new BackgroundObject("../img/3. Background/Layers/2. Floor/D2.png", -900),

    new BackgroundObject("../img/3. Background/Layers/5. Water/D1.png", 0),
    new BackgroundObject("../img/3. Background/Layers/4.Fondo 2/D1.png", 0),
    new BackgroundObject("../img/3. Background/Layers/3.Fondo 1/L1.png", 0),
    new BackgroundObject("../img/3. Background/Layers/2. Floor/D1.png", 0),

    new BackgroundObject("../img/3. Background/Layers/5. Water/D2.png", 900),
    new BackgroundObject("../img/3. Background/Layers/4.Fondo 2/D2.png", 900),
    new BackgroundObject("../img/3. Background/Layers/3.Fondo 1/L2.png", 900),
    new BackgroundObject("../img/3. Background/Layers/2. Floor/D2.png", 900),

    new BackgroundObject("../img/3. Background/Layers/5. Water/D1.png", 1800),
    new BackgroundObject("../img/3. Background/Layers/4.Fondo 2/D1.png", 1800),
    new BackgroundObject("../img/3. Background/Layers/3.Fondo 1/L1.png", 1800),
    new BackgroundObject("../img/3. Background/Layers/2. Floor/D1.png", 1800),
  ]
);
